name: E2E Tests

on: 
  push:
    branches:
      - "main"
env: 
  CYPRESS_BASE_URL: https://www.amazon.com

jobs:
  cypress-run:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
        
      - name: Setup
        run: npm install
        
      - name: Test
        run: |
          npm run clean-reports
          npm run e2e:run
      - name: Upload report chunks
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: cypress/reports
  
  cypress-report:
    if: always()
    needs: cypress-run
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
        
      - run: npm install
      - uses: actions/download-artifact@v3
        with:
          name: reports
          path: cypress/reports

      - name: Generate html report
        run: |
            npm run merge-reports
            npm run generate-report

      - name: Upload html report
        uses: actions/upload-artifact@v3
        with:
          name: mochareports
          path: mochareports
          retention-days: 7

      - uses: geekyeggo/delete-artifact@v2
        with:
          name: reports